---
loopback: 192.179.0.74
local_asn: 104
neighbors:
   - interface: ge-0/0/0
     name: ex4300-9
     asn: 109
     peer_ip: 192.168.0.1 
     local_ip: 192.168.0.0
     peer_loopback: 192.179.0.95
   - interface: ge-0/0/1 
     name: ex4300-17
     asn: 110
     peer_ip: 192.168.0.2
     local_ip: 192.168.0.3
     peer_loopback: 192.179.0.73
