---
loopback: 192.179.0.95
local_asn: 109
neighbors:
   - interface: ge-0/0/0
     name: ex4300-17
     asn: 110
     peer_ip: 192.168.0.4 
     local_ip: 192.168.0.5
     peer_loopback: 192.179.0.73
   - interface: ge-0/0/1  
     name: ex4300-18
     asn: 104
     peer_ip: 192.168.0.0
     local_ip: 192.168.0.1
     peer_loopback: 192.179.0.74
